### PR TITLE
Merge with upstream

### PR DESCRIPTION
**Pull request by stephyeung**
I missed that we added our own Tab behavior, so updating our fork of the library to still get the newest changes (e.g. the componentWillReceiveProps silencing), but keep our special behaviors. (I looked through previous issues/PRs in original library and seems like the Tab feature has been asked for and attempted multiple times, but doesn't look like any changes will be accepted soon.)

- Pulls in all the commits from upstream moroshko/react-autosuggest since Oct 2017
- Most of the logic around highlighting first suggestion changed, so I let the merge process overwrite https://github.com/range-labs/react-autosuggest/commit/a90857f1453366028c4a5e050a016f515705cef8 and re-committed https://github.com/range-labs/react-autosuggest/commit/8306b5a6257fc0ccb509e3679c2fa0a391cddefe
- Updates the `dist` files

Also... hope I did this right. I did
```
git reset --hard [last commit from moroshko/react-autosuggest we have] // Thought this would make the merge easier
git fetch upstream
git merge upstream/master
git rebase master // Resolved with the commits unique to our repo
```

### CODE REVIEW

**Review by seanami — APPROVED** [review]
👍 Wow, thank you Steph. Sorry this was such a pain to address.

Do you understand how 8306b5a addresses the "Tab doesn't choose the selected item" issue? It's been so long, I don't understand anymore...

**Comment by stephyeung** [comment]
The tab issue is was fixed in this commit from before: https://github.com/range-labs/react-autosuggest/commit/592a9d3f60eed6f1865a5d509f742b38e75478d9

There were no conflicts with it and I reconfirmed that the [change was still in the file](https://github.com/range-labs/react-autosuggest/blob/a5fe5f5150ab3f6ff034850ed7bb2c298d34f1d6/dist/Autosuggest.js#L657) after rebasing :+1:

**Comment by stephyeung** [comment]
https://github.com/range-labs/react-autosuggest/commit/8306b5a6257fc0ccb509e3679c2fa0a391cddefe is addressing something I noticed was broken again too (which I think the original commit was fixing too...) where it jumped to highlight the first selection in compose even if I pressed down in the menu, because some other props had changed?

**Comment by seanami** [comment]
@stephyeung Ah, got it. Thanks for the clarification! 👍

**Pull request merged**
